apiVersion: v2
name: policy-api-crds
description: This app contains the Policy API CRDs.
home: https://github.com/giantswarm/policy-api
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
version: 0.0.6
annotations:
  io.giantswarm.application.audience: all
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: shield
